### ISSUE TITLE
Only works if "Vibrate on Ring/Silence" is ON

### ISSUE THREAD

**Issue by jakobjw** [codyd51/CallConnect#1]
This only works if "Settings > Sounds > Vibrate on Ring" is ON (if silencer is switched off) and "Settings > Sounds > Vibrate on Silent" is ON (if silencer is switched on). This does not have to be a bug (can also be a feature since the user doesn't want the device to vibrate at all). That's a matter of opinion.

A workaround could be to change the line

AudioServicesPlaySystemSound(kSystemSoundID_Vibrate);

to

AudioServicesPlaySystemSound(1352); // 1352, which is working regardless of the silent switch or the settings on the device (Settings->vibrate on ring, vibrate on silent) // jakob.j 20150712

http://stackoverflow.com/a/22843899/1884907

**Comment by codyd51** [comment]
Thank you; commit 441b19be14a3e8b1453117c2a474ca3dafde5474 has implemented your described fix and resolved the issue.

An update has been sent to BigBoss with the new package.

Cheers,
-Phillip Tennen
